import type { Metadata } from 'next'
import Header from '@/src/components/layout/Header/Header'
import Footer from '@/src/components/layout/Footer/Footer'
import { Roboto, Gothic_A1 } from 'next/font/google'
import ScrollProgres from '@/src/components/UI/ScrollProgres'
import ScrollToTop from '@/src/helpers/ScrollToTop'
import './globals.css'

const roboto = Roboto({
	weight: ['400', '500', '700'],
	subsets: ['latin'],
	variable: '--font-roboto'
})

const gothicA1 = Gothic_A1({
	weight: ['400'],
	subsets: ['latin'],
	variable: '--font-gothic'
})

export const metadata: Metadata = {
	title: 'digital-project',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.variable} ${gothicA1.variable} antialiased`}>
				<ScrollToTop />
				<ScrollProgres />
				<Header />
				<main className='min-h-screen px-5 md:px-34'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
